// Post-build: generate out/sw.js with a precache manifest of the exported files
// so the app works offline immediately after the first visit. Paths are relative
// to the service-worker scope, so this stays correct under any basePath.
import { readdirSync, statSync, writeFileSync } from 'node:fs';
import { createHash as hash } from 'node:crypto';
import { join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const OUT = fileURLToPath(new URL('../out/', import.meta.url));
const PRECACHE_EXT = new Set(['.html', '.js', '.css', '.woff', '.woff2', '.png', '.svg', '.webmanifest', '.json', '.ico']);

function walk(dir) {
  const files = [];
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    const st = statSync(full);
    if (st.isDirectory()) files.push(...walk(full));
    else files.push(full);
  }
  return files;
}

const all = walk(OUT);
const assets = all
  .map((f) => relative(OUT, f).split('\\').join('/'))
  .filter((rel) => {
    if (rel === 'sw.js') return false;
    const dot = rel.lastIndexOf('.');
    return dot >= 0 && PRECACHE_EXT.has(rel.slice(dot));
  });

// Ensure the SPA entry is present and served for navigations.
const precache = Array.from(new Set(['index.html', './', ...assets]));

// Version = hash of the file list so each build gets a fresh cache.
const version = hash('sha1').update(precache.join('|')).digest('hex').slice(0, 12);

const sw = `// AUTO-GENERATED by scripts/gen-sw.mjs — do not edit by hand.
const CACHE = 'recipe-vault-${version}';
const PRECACHE = ${JSON.stringify(precache)};

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    // Cache what we can; ignore any single failure so install still succeeds.
    await Promise.all(PRECACHE.map((u) => cache.add(u).catch(() => {})));
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)));
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  const sameOrigin = url.origin === self.location.origin;

  // Single-page app: serve the cached shell for any navigation (online or off).
  if (req.mode === 'navigate') {
    event.respondWith((async () => {
      const cache = await caches.open(CACHE);
      try {
        const fresh = await fetch(req);
        cache.put('index.html', fresh.clone());
        return fresh;
      } catch {
        return (await cache.match('index.html')) || (await cache.match('./')) || Response.error();
      }
    })());
    return;
  }

  if (!sameOrigin) return; // cross-origin (e.g. seed photos): network only

  // Cache-first for same-origin assets, refresh in the background.
  event.respondWith((async () => {
    const cache = await caches.open(CACHE);
    const cached = await cache.match(req);
    const network = fetch(req).then((res) => {
      if (res && res.status === 200) cache.put(req, res.clone());
      return res;
    }).catch(() => cached);
    return cached || network;
  })());
});
`;

writeFileSync(join(OUT, 'sw.js'), sw);
console.log(`gen-sw: wrote out/sw.js (cache recipe-vault-${version}, ${precache.length} precached files)`);
